"""update name description

Revision ID: 0c5bc258f040
Revises: eb5d79731c44
Create Date: 2023-08-20 20:28:38.798578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5bc258f040'
down_revision = 'eb5d79731c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_column('descirption')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descirption', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
