"""update name description

Revision ID: 0c5bc258f040
Revises: eb5d79731c44
Create Date: 2023-08-20 20:28:38.798578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123f9a9bbd88'
down_revision = '194f9a9bbd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
