from app import app, db
from models.nlp.intent_model import Intent, Pattern, Response
from utils import FileUtil

# revision identifiers, used by Alembic.
revision = '194f9a9bbd99'
down_revision = '0c5bc258f040'
branch_labels = None
depends_on = None


def upgrade():
    with app.app_context():
        data = FileUtil.load_data_json("intents/intent4.json")
        intents = data["intents"]
        
        for intent in intents:
            new_intents = Intent(tag=intent['tag'])
            db.session.add(new_intents)
            db.session.commit()
            
            for pattern in intent['patterns']:
                try:
                    new_patterns = Pattern(pattern_text=pattern, intent_id=new_intents.id)
                    db.session.add(new_patterns)
                    db.session.commit()
                except Exception as ex:
                    pass
                
            for response in intent['responses']:
                try:
                    new_responses = Response(response_text=response, intent_id=new_intents.id)
                    db.session.add(new_responses)
                    db.session.commit()
                except Exception as ex:
                    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
