"""add description columns into config model

Revision ID: 277f27d56020
Revises: 6f764639ff83
Create Date: 2023-10-04 02:15:30.169151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277f27d56020'
down_revision = '6f764639ff83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
