"""add bool value columns into config model

Revision ID: 56793ea7bbc9
Revises: 277f27d56020
Create Date: 2023-10-04 02:33:41.880581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56793ea7bbc9'
down_revision = '277f27d56020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bool_value', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.drop_column('bool_value')

    # ### end Alembic commands ###
