"""add config model

Revision ID: 6f764639ff83
Revises: de97f46ae1d8
Create Date: 2023-10-04 02:01:08.629874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f764639ff83'
down_revision = 'de97f46ae1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_name', sa.String(length=255), nullable=True),
    sa.Column('string_value', sa.String(length=255), nullable=True),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_configs')
    # ### end Alembic commands ###
