"""add attribute for product

Revision ID: 77ceca2c8d8a
Revises: 123f9a9bbd88
Create Date: 2023-09-11 00:38:39.908158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ceca2c8d8a'
down_revision = '123f9a9bbd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.alter_column('message_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
