"""add attribute for product

Revision ID: 77ceca2c8d8b
Revises: 77ceca2c8d8a
Create Date: 2023-09-11 00:38:39.908158

"""
import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = '77ceca2c8d8b'
down_revision = '77ceca2c8d8a'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('attribute', sa.Column('attribute_name', sa.String(length=255), nullable=True))

    # Đường dẫn đến tệp list_attr_cloth.txt
    # attr_file_path = 'F:\\chatbotsupportcostume-main\\backend\\resources\\cnn\\list_attr_cloth.txt'  # Thay thế 'path_to_list_attr_cloth.txt' bằng đường dẫn thực tế
    # if os.path.exists(attr_file_path):
    #     with open(attr_file_path, 'r') as file:
    #         lines = file.readlines()
    #         for line in lines[2:]:
    #             attribute_name = line.strip()
    #             # Thêm thuộc tính vào cơ sở dữ liệu
    #             attribute = Attribute(attribute_name=attribute_name, attribute_type=1)  # Điều chỉnh 'attribute_type' nếu cần
    #             session = sessionmaker(bind=op.get_bind())()
    #             session.add(attribute)
    #             session.commit()

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute', 'attribute_name')

    # ### end Alembic commands ###