"""change type dictionary

Revision ID: 8b281e4a38d5
Revises: e6164d4dbcb2
Create Date: 2023-10-09 06:08:54.361731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b281e4a38d5'
down_revision = 'e6164d4dbcb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionaries', schema=None) as batch_op:
        batch_op.alter_column('synonyms',
               existing_type=sa.TEXT(),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionaries', schema=None) as batch_op:
        batch_op.alter_column('synonyms',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
