"""update order date

Revision ID: a22756c8ebce
Revises: 
Create Date: 2023-08-20 19:40:48.985452

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a22756c8ebce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='orderstatusenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'CANCELLED', name='orderstatusenum'),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
