"""create model cnn training

Revision ID: a9ec176a9b45
Revises: 3a3c4ea1ea8b
Create Date: 2023-10-01 07:04:37.246616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ec176a9b45'
down_revision = '3a3c4ea1ea8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fashion_net_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_file', sa.String(length=255), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('lr', sa.Float(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('epoch', sa.Integer(), nullable=True),
    sa.Column('attribute_loss', sa.Float(), nullable=True),
    sa.Column('blue_cates_loss', sa.Float(), nullable=True),
    sa.Column('blue_cates_top1', sa.Float(), nullable=True),
    sa.Column('blue_cates_top2', sa.Float(), nullable=True),
    sa.Column('blue_cates_top3', sa.Float(), nullable=True),
    sa.Column('blue_cates_top5', sa.Float(), nullable=True),
    sa.Column('blue_lands_loss', sa.Float(), nullable=True),
    sa.Column('concate_category_loss', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('val_attribute_loss', sa.Float(), nullable=True),
    sa.Column('val_blue_cates_loss', sa.Float(), nullable=True),
    sa.Column('val_blue_cates_top1', sa.Float(), nullable=True),
    sa.Column('val_blue_cates_top2', sa.Float(), nullable=True),
    sa.Column('val_blue_cates_top3', sa.Float(), nullable=True),
    sa.Column('val_blue_cates_top5', sa.Float(), nullable=True),
    sa.Column('val_blue_lands_loss', sa.Float(), nullable=True),
    sa.Column('val_concate_category_loss', sa.Float(), nullable=True),
    sa.Column('val_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fashion_net_models')
    # ### end Alembic commands ###
