"""add accuracy columns for model 

Revision ID: de97f46ae1d8
Revises: a9ec176a9b45
Create Date: 2023-10-04 01:27:16.814446

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'de97f46ae1d8'
down_revision = 'a9ec176a9b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fashion_net_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blue_cates_acc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('red_green_attrs_acc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('test_accuracy', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fashion_net_models', schema=None) as batch_op:
        batch_op.drop_column('test_accuracy')
        batch_op.drop_column('red_green_attrs_acc')
        batch_op.drop_column('blue_cates_acc')

    # ### end Alembic commands ###
