"""change column accuracy name

Revision ID: e6164d4dbcb2
Revises: 56793ea7bbc9
Create Date: 2023-10-07 14:37:48.274433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6164d4dbcb2'
down_revision = '56793ea7bbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fashion_net_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blue_cates_acc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('blue_lands_acc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('red_green_cates_acc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('red_green_attrs_acc', sa.Float(), nullable=True))
        batch_op.drop_column('attrs_acc')
        batch_op.drop_column('cates_acc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fashion_net_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cates_acc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('attrs_acc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('red_green_attrs_acc')
        batch_op.drop_column('red_green_cates_acc')
        batch_op.drop_column('blue_lands_acc')
        batch_op.drop_column('blue_cates_acc')

    # ### end Alembic commands ###
