"""delete model attribute

Revision ID: ee530764064e
Revises: c00fa0ed32fe
Create Date: 2023-09-16 14:55:16.453394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee530764064e'
down_revision = 'c00fa0ed32fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribute')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attribute_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('attribute_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='attribute_pkey')
    )
    # ### end Alembic commands ###
